* LyXiT
Edit \LaTeX fragment in LyX
* Motivation
Using with Vim/Evil/Emacs bang or shell command. It deserves a
dedicated binding if you're working with LaTeX directly or in org-mode
with a lot of formulae etc.

I tried my best to keep it working in both OS X/BSD and *nix world.
* Prerequisite
Make sure you have =lyx= and =tex2lyx= with the PATH environment variable.
* Example
** Emacs
#+BEGIN_SRC emacs-lisp
(require 'use-package)
(evil-define-operator link/lyxit-line (beg end type)
  "Edit current region in lyx."
  :motion evil-line
  (interactive "<R>")
  (shell-command-on-region beg end "lyxit -n -" t t)
  (when org-indent-mode
    (org-indent-mode 1)))
(bind-key "s-m" 'link/lyxit-line org-mode-map)
#+END_SRC
** Vim/Evil
#+BEGIN_SRC vim
:'<,'>!lyxit
#+END_SRC

* License
MIT
#+BEGIN_QUOTE
Copyright (c) 2015 Quang-Linh LE

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+END_QUOTE
